site_name: BCS 4.0 User Guide

pages:
- [index.md, Home]
- [ui.md, User Interface]
- [finder.md, BCS Finder]
- [utilities.md, Online Utilities]
- [main_control.md, Main Control]
- [data_log.md, Datalog]
- [process_editor.md, Process Editor]
- [temp_adjust.md, Temp Setpoint Adjust]
- [ladder_logic.md, Ladder Logic]
- [settings.md, Settings]
- [examples.md, Configuration Examples]


theme: ReadTheDocs
